dist: trusty
sudo: true
language: generic
branches:
  only:
    - plugin_v2

install:
  - sudo pip install tox
python:
  - "3.5"

# command to run tests
script:
  - sudo tox -e py35 --  test.test_hpe_plugin_v2
