dist: xenial
sudo: false
language: generic
branches:
  only:
    - plugin_v2

install:
  - sudo pip install tox
python:
  - "3.4"

matrix:
  include:
  - python: "3.4"
    env: TOXENV=py34

# command to run tests
script:
  - tox -e py34 --  test.test_hpe_plugin_v2
