dist: xenial
sudo: true
language: generic
branches:
  only:
    - plugin_v2

install:
  - sudo pip install tox
  
matrix:
  include:
 	- python: "3.5"
 	env: TOXENV=py35

# command to run tests
script:
  - tox -e py27 --  test.test_hpe_plugin_v2
  


