dist: xenial
sudo: true
language: generic
branches:
  only:
    - plugin_v2
before_install:
   sudo sudo rm /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/cache/apt/archives/lock
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

install:
  - sudo pip install tox
python:
  - "3.5"

matrix:
  include:
  - python: "3.5"
    env: TOXENV=py35

# command to run tests
script:
  - tox --  test.test_hpe_plugin_v2
