- name: Install prerequisites
  hosts: all
  tasks:
    - name: load plugin settings
      include_vars: 'properties/plugin_configuration_properties.yml'

    - name: Get the password
      shell: hpe3parencryptor -a {{INVENTORY[item[0]]['encryptor_key']}} "{{ INVENTORY[item[0]][(item[1].value)] }}"
      ignore_errors: yes
      register: passwords
      ignore_errors: yes
      with_nested:
        - "{{ INVENTORY.keys()}}"
        - [{ option: 'hpe3par_password', value: 'hpe3par_password' }, { option: 'san_password', value: 'hpe3par_password' }]


    #- name: Display password
    #  debug:
    #    msg: "{{ passwords }}"
        
    #- name: Display password
    #  debug:
    #    msg: "{{ passwords['results'][item | int]['item'] }} "
    #  with_items:
    #    - "{{ lookup('sequence','start=0 end=3',wantlist=True) }}"
        
    #- name: Display password
    #  debug:
    #    msg: "{{ passwords['results'][item | int]['stdout_lines'][0] }} "
    #  with_items:
    #    - "{{ lookup('sequence','start=0 end='+((INVENTORY.keys() | count)*2 -1) #|string,wantlist=True) }}"     
      
        
    #- name: Display password
    #  debug:
    #    msg: "{{ passwords['results'][0]['item'][0] }}"
       
    #- name: Display password
    #  debug:
    #    msg: "{{ passwords['results'][1]['item'][0] }}"

    #- name: Display password
    #  debug:
    #    msg: "{{ lookup('sequence','start=0 end='+((INVENTORY.keys() | count) -1) #|string,wantlist=True) }}"

    - name: Populate hpe.conf
      ini_file:
        path: /etc/hpedockerplugin/hpe.conf
        section: "{{ passwords['results'][item | int]['item'][0] }}"
        option:  "{{ passwords['results'][item | int]['item'][1]['option'] }}"
        value: "{{ passwords['results'][item | int]['stdout_lines'][0].split('password: ')[1] }} "
        no_extra_spaces: true
      with_items:
        - "{{ lookup('sequence','start=0 end='+((INVENTORY.keys() | count)*2 -1) |string,wantlist=True) }}"
      become: yes

