INVENTORY:
  DEFAULT:
    # Set of mandatory properties
    host_etcd_port_number: 23790
    hpedockerplugin_driver: hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
    hpe3par_ip: 15.212.192.251
    hpe3par_username: 3paradm
    hpe3par_password: 3pardata
    hpe3par_cpg: FC_r1

    # Required only in DEFAULT backend
    volume_plugin: dockerciuser/legacyvolumeplugin:plugin_v2

    # Set of optional parameters
    # If encryptor key is set, the passwords in hpe.conf would be encrypted
    encryptor_key: first_key
    #ssh_hosts_key_file: '/root/.ssh/known_hosts'
    logging: DEBUG
    #hpe3par_debug: True
    #suppress_requests_ssl_warning: True
    #hpe3par_snapcpg: FC_r1
    #hpe3par_iscsi_chap_enabled: True
    #use_multipath: False
    #enforce_multipath: False

  3PAR1:
    # Set of mandatory properties
    host_etcd_port_number: 23790
    hpedockerplugin_driver: hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
    hpe3par_ip: 15.212.192.252
    hpe3par_username: 3paradm
    hpe3par_password: 3pardata
    hpe3par_cpg: FC_r1

    # Set of optional parameters
    # If encryptor key is set, the passwords in hpe.conf would be encrypted
    encryptor_key: second_key
    logging: DEBUG
    #hpe3par_debug: True
    #suppress_requests_ssl_warning: True
    #hpe3par_snapcpg: FC_r1
    #hpe3par_iscsi_chap_enabled: True
    #use_multipath: False
    #enforce_multipath: False
    #ssh_hosts_key_file: '/root/.ssh/known_hosts'

