---
  - name: load etcd settings	
    include_vars: '../properties/etcd_properties.yml'	

   - name: Install FlexVolume drivers	
    copy:	
      src: "{{ item }}"	
      dest: "{{ driver_path }}"	
      owner: "root"	
      mode: 0755	
    with_fileglob:	
      - "../files/dory/*"	
